{% set name = "baderkit" %}
{% set version = "0.8.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/baderkit-{{ version }}.tar.gz
  sha256: 2de77d9a30da3e613f293455e1756d778f6521da52d3f4758ca7ea1bc841ca36

build:
  entry_points:
    - baderkit = baderkit.command_line.base:baderkit_app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26.0,<3.0
    - pandas >=2.1.0,<3.0
    - typer >=0.6.1,<=0.20.0
    - pymatgen >=2022.1.9,<=2025.10.7
    - scipy >=1.7.2,<2.0
    - numba >=0.59.0,<=0.62.1
    - rich >=11.0,<=14.2

test:
  imports:
    - baderkit
  commands:
    - pip check
    - baderkit --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SWeav02/baderkit
  summary: "A python implementation of Bader's Quantum Theory of Atoms in Molecules"
  description: |
    This module is a python reimplementaion of the Henkelman Group's Bader code built on numba, numpy, and pymatgen.
  doc_url: https://sweav02.github.io/baderkit/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - SWeav02
