{% set name = "baderkit" %}
{% set version = "0.2.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/baderkit-{{ version }}.tar.gz
  sha256: 9d880d29b44084d20a4059126782d1841dacd243635101abe590de7ceaf734b1

build:
  entry_points:
    - baderkit = baderkit.command_line.base:baderkit_app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26.0,<=2.3.1
    - pandas >=2.1.0,<=2.3.0
    - typer >=0.6.1,<=0.16.0
    - pymatgen >=2022.1.9,<=2025.6.14
    - scipy >=1.7.2,<=1.16.0
    - numba >=0.59.0,<=0.61.2
    - rich >=11.0,<=14.0

test:
  imports:
    - baderkit
  commands:
    - pip check
    - baderkit --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SWeav02/baderkit
  summary: "A python implementation of Bader's Quantum Theory of Atoms in Molecules"
  description: |
    This module is a python reimplementaion of the Henkelman Group's Bader code built on numba, numpy, and pymatgen.
  doc_url: https://sweav02.github.io/baderkit/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - SWeav02
